{% set name = "flake8-logging" %}
{% set version = "1.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 5347f77e746669d2a49d22f251f7a648bbdf285b7140b69aa867f7b42a29da96

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - flake8 !=3.2.0,>=3.0

test:
  imports:
    - flake8_logging
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/adamchainz/flake8-logging
  summary: A Flake8 plugin that checks for issues using the standard library logging module.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
