{% set name = "flake8-logging" %}
{% set version = "1.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 6ad85b386f3e5a65f44ea150dcc878920150813252cded0af7bc41f50be4082d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools
    - pip
  run:
    - python >=3.8
    - flake8 !=3.2.0,>=3.0

test:
  imports:
    - flake8_logging
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/adamchainz/flake8-logging
  summary: A Flake8 plugin that checks for issues using the standard library logging module.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
