{% set name = "flake8-logging" %}
{% set version = "1.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/flake8_logging-{{ version }}.tar.gz
  sha256: 255fe41b0fc4276d7e9cabea7969a6a0b4d85720409ab5a6dc71ff0be66fd4fd

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools
    - pip
  run:
    - python >=3.8
    - flake8 !=3.2.0,>=3.0

test:
  imports:
    - flake8_logging
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/adamchainz/flake8-logging
  summary: A Flake8 plugin that checks for issues using the standard library logging module.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
